
---
aleph:
  port:
    oauth: 18081
    finance: 18091
    media: 18100
    acquisitions: 18110
    adsales: 18120
    contentdelivery: 18130
    depreciation: 18140
    entities: 18150
    prebilling: 18160
    programming: 18170
    titles: 18180
    config: 18191
    branding: 18200

    commondb: 1521

  frontport:
    oauth: 18082
    finance: 18092
    media: 18102
    acquisitions: 18112
    adsales: 18122
    contentdelivery: 18132
    depreciation: 18142
    entities: 18152
    prebilling: 18162
    programming: 18172
    titles: 18182
    branding: 18202

  db:
    host: db.turner.dev.redb.ee
    sid: ALEPHDBTR1 

  oauth:
    context-path: /aleph-oauth
    uri: http://preprod.oauth.aleph.turner.com
    redis: 
      enabled: true
      host: argalephdockertpp2
      port: 6379

---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: false
  host: turner.com

---
spring:
  datasource:
    url: jdbc:oracle:thin:@argalephdbqa.turner.com:1521/ARGALEPHDBQA 
    username: proxy
    password: '{cipher}99e803146a8696911226f21fd6bd751aed363588ff5da31a5fdc602294a16169'
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  oauth2:
    resource:
      userInfoUri: ${aleph.oauth.uri}/user
  auth:
    serverurl: ${aleph.oauth.uri}/oauth/check_token

---
management:
  security:
    enabled: false  
  context-path: /manage
