
---
aleph:
  port:
    oauth: 18080
    finance: 18090
    media: 18100
    acquisitions: 18110
    adsales: 18120
    contentdelivery: 18130
    depreciation: 18140
    entities: 18150
    prebilling: 18160
    programming: 18170
    titles: 18180
    config: 18190
    branding: 18200

    commondb: 1521

  frontport:
    oauth: 18082
    finance: 18092
    media: 18102
    acquisitions: 18112
    adsales: 18122
    contentdelivery: 18132
    depreciation: 18142
    entities: 18152
    prebilling: 18162
    programming: 18172
    titles: 18182
    branding: 18202

  db:
    host: db.turner.dev.redb.ee
    sid: ALEPHDBD1 

  oauth:
    context-path: 
    uri: http://oauth.aleph.turner.com
    redis:
      enabled: true    
      host: argalephdockerprod1
      port: 6379
---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: false
  host: turner.com

---
spring:
  datasource:
    url: jdbc:oracle:thin:@argalephdbprod.turner.com:1530/ALEPHPR_SERVICE.turner.com
    username: proxy
    password: '{cipher}1711c7ab1c1c70c07be977589370fe2e057ebe9c3d032d86e654715179cd2485'
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  oauth2:
    resource:
      userInfoUri: ${aleph.oauth.uri}/user
  auth:
    serverurl: ${aleph.oauth.uri}/oauth/check_token

management:
  security:
    enabled: false
  context-path: /manage

server:
  tomcat:
    accessLogEnabled: true
    basedir: /log
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Real-IP

