
---
giu:
  port:
    oauth: 18080
    config: 18190

  frontport:
    oauth: 18082

  oauth:
    context-path: /giu-oauth
    uri: http://localhost:${giu.port.oauth}${giu.oauth.context-path}
    redis: 
      enabled: false
      host: localhost
      port: 6379
---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: true
  host: giu.com

---
spring:
  datasource:
    url: jdbc:oracle:thin:@${giu.db.host}:${giu.port.commondb}/${giu.db.sid}
    username: proxy
    password: proxy
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  oauth2:
    resource:
      userInfoUri: ${giu.oauth.uri}/user
  auth:
    serverurl: ${giu.oauth.uri}/oauth/check_token

---
management:
  security:
    enabled: false
  context-path: /manage
