
---
giu:
  port:
    oauth: 18080
    config: 18190

    commondb: 1521

  frontport:
    oauth: 18082

  db:
    host: repo.dev.redbee.io
    sid: GIUDBD1

  oauth:
    context-path: /giu-oauth
    uri: http://argalephdockerd1:${giu.port.oauth}${giu.oauth.context-path}
    redis: 
      enabled: false
      host: localhost
      port: 6379
---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: false
  host: turner.com

---
spring:
  datasource:
    url: jdbc:oracle:thin:@argalephdbd1.turner.com:1521/ALEPHDBD1 
    username: proxy
    password: proxy
    #driver-class-name: oracle.jdbc.driver.OracleDriver
    pool-name: SpringBootHikariCP
    type: com.zaxxer.hikari.HikariDataSource
    pool-prepared-statements: true
    max-open-prepared-statements: 250

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  oauth2:
    resource:
      userInfoUri: ${giu.oauth.uri}/user
  auth:
    serverurl: ${giu.oauth.uri}/oauth/check_token

---
management:
  security:
    enabled: false
  context-path: /manage

encrypt:
  key: turner
