
---
giu:
  port:
    oauth: 18080
    finance: 18090
    media: 18100
    acquisitions: 18110
    adsales: 18120
    contentdelivery: 18130
    depreciation: 18140
    entities: 18150
    prebilling: 18160
    programming: 18170
    titles: 18180
    config: 18190
    branding: 18200

    commondb: 1521

  frontport:
    oauth: 18082
    finance: 18092
    media: 18102
    acquisitions: 18112
    adsales: 18122
    contentdelivery: 18132
    depreciation: 18142
    entities: 18152
    prebilling: 18162
    programming: 18172
    titles: 18182
    branding: 18202

  db:
    host: repo.dev.redbee.io
    sid: GIUDBD1 

  oauth:
    context-path: /giu-oauth
    uri: http://localhost:${giu.port.oauth}${giu.oauth.context-path}
    redis: 
      enabled: false
      host: localhost
      port: 6379
---
ldap:
  url: ldap://argtbsdc01.turner.com:389
  mocked: true
  host: turner.com

---
spring:
  datasource:
    url: jdbc:oracle:thin:@${giu.db.host}:${giu.port.commondb}/${giu.db.sid}
    username: proxy
    password: proxy
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle9Dialect

  oauth2:
    resource:
      userInfoUri: ${giu.oauth.uri}/user
  auth:
    serverurl: ${giu.oauth.uri}/oauth/check_token

---
management:
  security:
    enabled: false
  context-path: /manage
